### PR TITLE
Don't panic, handle errors.

### LINKED ISSUE #33: Handle "peer <id> is not online"
nolooking_1   | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Lnd(Generic(Status { code: Unknown, message: "peer 028624b5cb872511d8b23a25ec351f6201af7e6b640edc0888fce05a8dede2bc8a is not online", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }))', src/http.rs:69:83

either
- return the error, ask receiver server control panel user to pick another peer or try again
- proceed w/o that peer

### PR DESCRIPTION
**Pull request by DanGould**
Fix "`unwrap()`s everywhere" disclaimer by handling errors. They still need to propagate to the UI.

HttpErrors still need to be returned with proper HTTP status codes

There are still 2 unwraps on mutex locks `let mut pj_by_spk = self.pjs.lock().unwrap();` which should probably panic with `expect` instead. What do you think?

I also need to add @evanlinjin as co-author of the HttpError. Work from #10 finally making it in!

fix #33

#50 *could* be fixed in this PR by pushing an update to the front end. but this at least responds by passing the error to the sender where they should end up in logs

### CODE REVIEW

File: src/http.rs [hunk 1]
```diff
@@ -45,77 +46,151 @@ async fn handle_web_req(
     req: Request<Body>,
     endpoint: url::Url,
 ) -> Result<Response<Body>, hyper::Error> {
-    use std::path::Path;
+    let result = match (req.method(), req.uri().path()) {
+        (&Method::GET, "/pj") => handle_index().await,
```
Comment (nickfarrow) [inline src/http.rs:50]: nice 👍

File: src/http.rs [hunk 2]
```diff
@@ -45,77 +46,151 @@ async fn handle_web_req(
...
+async fn handle_pj(scheduler: Scheduler, req: Request<Body>) -> Result<Response<Body>, HttpError> {
+    dbg!(req.uri().query());
 
-        // Return the 404 Not Found for other routes.
-        _ => {
-            let mut not_found = Response::default();
-            *not_found.status_mut() = StatusCode::NOT_FOUND;
-            Ok(not_found)
+    let headers = Headers(req.headers().to_owned());
+    let query = {
```
Comment (nickfarrow) [inline src/http.rs:90]: I couldn't find a cleaner way of getting around not having `Copy`..

File: src/http.rs [hunk 3]
```diff
@@ -45,77 +46,151 @@ async fn handle_web_req(
...
+        if let Some(query) = uri.query() {
+            Some(&query.to_owned());
         }
-    }
+        None
+    };
+    let body = req.into_body();
+    let bytes = hyper::body::to_bytes(body).await?;
+    dbg!(&bytes); // this is correct by my accounts
+    let reader = &*bytes;
```
Comment (nickfarrow) [inline src/http.rs:100]: Do we actually want to dbg! these bytes?

File: src/http.rs [hunk 4]
```diff
@@ -45,77 +46,151 @@ async fn handle_web_req(
...
+    /// Transforms an [HttpError] into a HTTP response
+    pub fn into_response(self) -> Result<Response<Body>, hyper::Error> {
+        if let Self::Hyper(err) = self {
+            return Err(err);
+        }
+
+        let resp = Response::new(Body::from(self.to_string()));
+        let (mut parts, body) = resp.into_parts();
+
+        // TODO respond with well known errors as defined in BIP-0078
```
Comment (nickfarrow) [inline src/http.rs:152]: Will this also give us more informative errors on most senders?

**Comment by nickfarrow** [comment]
Looks good to me! Great stuff.

Yep expect sounds right to use `expect`s there, probably not worth retries or anything complex

File: src/http.rs (hunk 4 above)
Comment (DanGould) [reply src/http.rs:152]: The only difference to start would be UI would say

"not-enough-money | The receiver added some inputs but could not bump the fee of the payjoin proposal."

or

"original-psbt-rejected | The receiver rejected the original PSBT. "

otherwise the spec says to put errors into logs only. This becomes more useful when we're using our own sender because we can show can decide to propagate new well-known errors into our UIs.

https://github.com/bitcoin/bips/blob/master/bip-0078.mediawiki#receivers-well-known-errors

File: src/http.rs (hunk 3 above)
Comment (DanGould) [reply src/http.rs:100]: It has let us check the original PSBT in the past. Of little use here. We could introduce the log crate to show debug/warn/errors logging soon

Comment (DanGould) [reply src/http.rs:99]: removed it for this pr
